### ISSUE TITLE
sdk缺少/amis/sdk/thirds/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf文件

### ISSUE THREAD

**Issue by Lzw2016** [baidu/amis#1203] opened 2020-12-18 06:57 UTC
#### 描述问题：
sdk缺少/amis/sdk/thirds/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf文件

#### 截图或视频：

![image](https://user-images.githubusercontent.com/19291563/102584373-4a4a6000-4141-11eb-978c-29bb5e455175.png)

**Comment by RickCole21** [comment] 2020-12-25 08:57
Duplicate of #1163

**Comment by RickCole21** [comment] 2020-12-31 08:06
最新版已修复：https://github.com/baidu/amis/releases/tag/1.1.0

**Closed** 2021-01-04 06:36 UTC
Labels: need confirm
